"use client";

import { motion } from "framer-motion";
import { ArrowRight, GitBranch, Star } from "lucide-react";
import * as React from "react";

import { Topbar } from "@/components/topbar";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { getPulse, type GitHubPulse } from "@/lib/api";

export default function PulsePage() {
  const [username, setUsername] = React.useState("octocat");
  const [loading, setLoading] = React.useState(false);
  const [data, setData] = React.useState<GitHubPulse | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    try {
      const res = await getPulse(username.trim());
      setData(res);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-[radial-gradient(60%_60%_at_50%_0%,rgba(34,211,238,0.14),rgba(2,6,23,0)_70%)]">
      <Topbar />
      <main className="py-10">
        <Container>
          <div className="flex items-start justify-between gap-6 flex-col lg:flex-row">
            <div className="w-full lg:max-w-xl space-y-3">
              <h1 className="text-2xl font-semibold tracking-tight text-slate-50">
                GitHub Pulse
              </h1>
              <p className="text-sm text-slate-300">
                Enter a GitHub username to generate a recruiter-style score and
                3 high-impact improvements.
              </p>

              <div className="mt-4 flex gap-2">
                <div className="flex h-11 flex-1 items-center gap-2 rounded-xl bg-white/5 px-3 shadow-[0_0_0_1px_rgba(148,163,184,0.15)]">
                  <GitBranch className="h-4 w-4 text-slate-400" />
                  <input
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    className="w-full bg-transparent text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none"
                    placeholder="e.g. tejas9406"
                  />
                </div>
                <Button onClick={run} disabled={loading || !username.trim()}>
                  {loading ? "Scoring..." : "Score"}
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </div>

              {error ? (
                <div className="mt-3 rounded-2xl bg-red-500/10 px-4 py-3 text-sm text-red-200 shadow-[0_0_0_1px_rgba(248,113,113,0.25)]">
                  {error}
                </div>
              ) : null}
            </div>

            <div className="w-full lg:flex-1">
              {data ? (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.25 }}
                  className="rounded-3xl bg-gradient-to-b from-white/8 to-white/3 p-6 shadow-[0_0_0_1px_rgba(148,163,184,0.18)]"
                >
                  <div className="flex items-center justify-between gap-4">
                    <div>
                      <div className="text-xs text-slate-400">
                        Recruiter-Ready Score
                      </div>
                      <div className="mt-1 text-5xl font-semibold tracking-tight text-cyan-300">
                        {data.score}
                      </div>
                    </div>
                    <div className="rounded-2xl bg-white/5 px-3 py-2 text-xs text-slate-300 shadow-[0_0_0_1px_rgba(148,163,184,0.15)]">
                      Generated by{" "}
                      <span className="text-slate-100">{data.generated_by}</span>
                    </div>
                  </div>

                  <div className="mt-5 grid gap-3">
                    {data.recruiter_tips.map((t, idx) => (
                      <div
                        key={idx}
                        className="rounded-2xl bg-slate-950/50 px-4 py-3 text-sm text-slate-200 shadow-[inset_0_0_0_1px_rgba(148,163,184,0.12)]"
                      >
                        {t}
                      </div>
                    ))}
                  </div>

                  <div className="mt-6">
                    <div className="text-xs font-medium text-slate-400">
                      Top repos
                    </div>
                    <div className="mt-3 grid gap-3 sm:grid-cols-2">
                      {data.top_repos.map((r) => (
                        <a
                          key={r.full_name}
                          className="rounded-2xl bg-white/5 p-4 shadow-[0_0_0_1px_rgba(148,163,184,0.15)] hover:bg-white/7 transition-colors"
                          href={r.html_url}
                          target="_blank"
                          rel="noreferrer"
                        >
                          <div className="flex items-start justify-between gap-2">
                            <div className="text-sm font-medium text-slate-100">
                              {r.name}
                            </div>
                            <div className="flex items-center gap-1 text-xs text-slate-300">
                              <Star className="h-3.5 w-3.5 text-cyan-300" />
                              {r.stargazers_count}
                            </div>
                          </div>
                          <div className="mt-1 text-xs text-slate-400">
                            {r.language || "—"}{" "}
                            {r.description ? `· ${r.description}` : ""}
                          </div>
                        </a>
                      ))}
                    </div>
                  </div>
                </motion.div>
              ) : (
                <div className="rounded-3xl bg-white/3 p-10 text-sm text-slate-400 shadow-[0_0_0_1px_rgba(148,163,184,0.12)]">
                  Run a score to see results here.
                </div>
              )}
            </div>
          </div>
        </Container>
      </main>
    </div>
  );
}

